### ISSUE TITLE
[BUG] Octolapse doesn't work on raspi docker build

### ISSUE THREAD

**Issue by hemna** [OctoPrint/octoprint-docker#184]
```
│2021-03-17 16:35:28,369 - octolapse.render - ERROR - Rendering Error                                                                            │
│Traceback (most recent call last):                                                                                                              │
│  File "/octoprint/plugins/lib/python3.8/site-packages/octoprint_octolapse/render.py", line 1720, in _render                                    │
│    self._add_text_overlays()                                                                                                                   │
│  File "/octoprint/plugins/lib/python3.8/site-packages/octoprint_octolapse/render.py", line 2158, in _add_text_overlays                         │
│    img = self.add_overlay(img,                                                                                                                 │
│  File "/octoprint/plugins/lib/python3.8/site-packages/octoprint_octolapse/render.py", line 2213, in add_overlay                                │
│    font = ImageFont.truetype(font_path, size=font_size)                                                                                        │
│  File "/octoprint/plugins/lib/python3.8/site-packages/PIL/ImageFont.py", line 852, in truetype                                                 │
│    return freetype(font)                                                                                                                       │
│  File "/octoprint/plugins/lib/python3.8/site-packages/PIL/ImageFont.py", line 849, in freetype                                                 │
│    return FreeTypeFont(font, size, index, encoding, layout_engine)                                                                             │
│  File "/octoprint/plugins/lib/python3.8/site-packages/PIL/ImageFont.py", line 173, in __init__                                                 │
│    freetype_version = parse_version(features.version_module("freetype2"))                                                                      │
│  File "/octoprint/plugins/lib/python3.8/site-packages/packaging/version.py", line 57, in parse                                                 │
│    return Version(version)                                                                                                                     │
│  File "/octoprint/plugins/lib/python3.8/site-packages/packaging/version.py", line 296, in __init__                                             │
│    match = self._regex.search(version)                                                                                                         │
│TypeError: expected string or bytes-like object
```

I believe it's a failure in the PIL cpython lib installed in the container.

The reference issue in octolapse here:
https://github.com/FormerLurker/Octolapse/issues/710

**Comment by LongLiveCHIEF** [comment]
Is this just for awareness, or are we thinking there's something with the docker build that can be done to resolve the issue in our image?
